"""Repository protocol — the persistence contract (ARCHITECTURE.md §2, §9).

The deterministic Engine and all services depend on this protocol, never on a
concrete repository. Two implementations satisfy it:

  * :class:`~bookmind.storage.in_memory.InMemoryRepository` — the in-process
    implementation used by deterministic tests;
  * :class:`~bookmind.storage.sql.repository.SqlRepository` — the SQLite /
    PostgreSQL impl that survives restarts (PRODUCTIZATION M1).

Adding a third (e.g. a test double) only requires satisfying this protocol.

``ScopeError`` is raised on any cross-project / cross-user / unauthorized
access and is defined at the storage boundary.
"""

from __future__ import annotations

from contextlib import contextmanager
from typing import TYPE_CHECKING, Protocol, runtime_checkable

# Re-export from the storage boundary; the in-memory module also imports this
# symbol for compatibility with older callers.
from .errors import ScopeError  # noqa: F401  (re-export)

if TYPE_CHECKING:
    from ..jobs.job_store import IngestionJob
    from ..domain.enums import UIPreset
    from ..domain.models import (
        Book,
        Concept,
        ConceptRelation,
        Conversation,
        Message,
        Evidence,
        LearnerConceptState,
        LearningProject,
        MisconceptionHypothesis,
        ProjectBook,
        Run,
        RunEvent,
        StateTransition,
        User,
    )
    from ..retrieval.chunk import DocumentChunk
    from ..retrieval.fusion import HybridRetriever


@runtime_checkable
class Repository(Protocol):
    """The persistence entry point implemented by every storage backend.

    Concurrency: ``save_state`` uses optimistic concurrency on ``state.version``.
    Idempotency: ``append_evidence`` returns False (no write) iff the
    ``event_key`` already exists. ``record_expiry_key`` is a set membership test.
    """

    # --- identity / scoping ------------------------------------------------
    def transaction(self): ...
    def add_user(self, user: "User") -> None: ...
    def get_user(self, user_id: str) -> "User | None": ...
    def create_project(self, project: "LearningProject") -> None: ...
    def get_project(self, project_id: str) -> "LearningProject | None": ...
    def projects_for_user(self, learner_id: str) -> list["LearningProject"]: ...
    def assert_project_owned_by(self, project_id: str, learner_id: str) -> "LearningProject": ...
    def archive_project(self, project_id: str) -> bool: ...
    def update_project(self, project_id: str, *, name: str | None = None,
                       goal: str | None = None, learning_scope: str | None = None,
                       deadline: str | None = None, current_plan: str | None = None,
                       last_source_id: str | None = None,
                       last_source_page: int | None = None,
                       default_mode: "UIPreset | None" = None) -> None: ...
    def get_project_mode(self, project_id: str) -> "UIPreset | None": ...

    # --- ingestion jobs ---------------------------------------------------
    def save_ingestion_job(self, job: "IngestionJob") -> None: ...
    def get_ingestion_job(self, job_id: str) -> "IngestionJob | None": ...
    def ingestion_jobs_for_project(self, project_id: str) -> list["IngestionJob"]: ...
    def latest_ingestion_job_for_book(self, book_id: str,
                                      project_id: str | None = None) -> "IngestionJob | None": ...
    def recover_running_ingestion_jobs(self) -> list["IngestionJob"]: ...
    def pending_ingestion_jobs(self) -> list["IngestionJob"]: ...

    # --- conversations / runs --------------------------------------------
    def save_conversation(self, conversation: "Conversation") -> None: ...
    def conversations_for_project(self, project_id: str,
                                  activity_type: str | None = None) -> list["Conversation"]: ...
    def get_conversation_record(self, conversation_id: str) -> "Conversation | None": ...
    def rename_conversation_record(self, conversation_id: str,
                                   title: str) -> "Conversation | None": ...
    def delete_conversation_record(self, conversation_id: str) -> bool: ...
    def save_message(self, message: "Message") -> None: ...
    def messages_for_conversation(self, conversation_id: str) -> list["Message"]: ...
    def save_run_record(self, run: "Run") -> None: ...
    def get_run_record(self, run_id: str) -> "Run | None": ...
    def find_run_record(self, conversation_id: str, idempotency_key: str) -> "Run | None": ...
    def save_run_event_records(self, events: list["RunEvent"]) -> None: ...
    def run_event_records(self, run_id: str, *, after_sequence: int = -1) -> list["RunEvent"]: ...

    def add_book(self, book: "Book") -> None: ...
    def get_source(self, source_id: str) -> "Book | None": ...
    def find_source_by_hash(self, learner_id: str, source_hash: str) -> "Book | None": ...
    def update_source_metadata(self, source_id: str, *, parser_version: str | None = None,
                               page_count: int | None = None,
                               section_count: int | None = None,
                               outline: list[dict] | None = None) -> None: ...
    def link_book(self, pb: "ProjectBook") -> None: ...
    def allowed_book_ids(self, project_id: str, *, only_enabled: bool = True) -> set[str]: ...
    def book_accessible_by(self, book_id: str, learner_id: str) -> bool: ...

    # --- concepts ----------------------------------------------------------
    def add_concept(self, concept: "Concept") -> None: ...
    def concepts_for_book(self, book_id: str) -> list["Concept"]: ...
    def replace_book_graph(
        self, book_id: str, concepts: list["Concept"], relations: list["ConceptRelation"]
    ) -> None: ...
    def relations_for_book(self, book_id: str) -> list["ConceptRelation"]: ...
    def concept_in_project_scope(self, concept_id: str, project_id: str) -> bool: ...

    # --- learner state -----------------------------------------------------
    def get_state(self, project_id: str, concept_id: str) -> "LearnerConceptState": ...
    def save_state(self, state: "LearnerConceptState") -> None: ...

    # --- evidence ----------------------------------------------------------
    def append_evidence(self, evidence: "Evidence") -> bool: ...
    def evidence_for(self, project_id: str, concept_id: str) -> list["Evidence"]: ...
    def evidence_for_misconception(self, project_id: str, bug_id: str) -> list["Evidence"]: ...
    def evidence_for_project(self, project_id: str) -> list["Evidence"]: ...

    # --- trusted tasks / submissions (M4) ----------------------------------
    def save_trusted_task(self, task_data: dict) -> None: ...
    def get_trusted_task(self, task_id: str) -> dict | None: ...
    def pending_task_for_conversation(self, conversation_id: str) -> dict | None: ...
    def pending_task_for_project(self, project_id: str) -> dict | None: ...
    def update_task_status(self, task_id: str, status: str, *, last_submission_id: str | None = None) -> None: ...
    def increment_task_hints(self, task_id: str) -> int: ...
    def save_submission(self, submission_data: dict) -> bool: ...
    def get_submission_by_idem(self, task_id: str, idempotency_key: str) -> dict | None: ...

    # --- misconceptions ----------------------------------------------------
    def get_misconception(self, project_id: str, bug_id: str) -> "MisconceptionHypothesis | None": ...
    def upsert_misconception(self, mis: "MisconceptionHypothesis") -> None: ...
    def all_misconceptions(self, project_id: str) -> list["MisconceptionHypothesis"]: ...

    # --- transitions -------------------------------------------------------
    def record_transition(self, t: "StateTransition") -> None: ...
    def transitions_for(self, project_id: str, *, entity_type: str | None = None,
                        entity_id: str | None = None) -> list["StateTransition"]: ...

    # --- expiry idempotency (LEARNING_MODEL §6) ---------------------------
    def record_expiry_key(self, key: str) -> None: ...
    def expiry_keys(self) -> set[str]: ...

    # --- retrieval artifacts -----------------------------------------------
    def add_chunks(self, book_id: str, chunks: list["DocumentChunk"]) -> None: ...
    def chunks_for_book(self, book_id: str) -> list["DocumentChunk"]: ...
    def chunks_for_project(self, project_id: str, *, only_enabled: bool = True) -> list["DocumentChunk"]: ...
    def chunk_by_id(self, chunk_id: str) -> "DocumentChunk | None": ...
    def set_retriever(self, project_id: str, retriever: "HybridRetriever") -> None: ...
    def get_retriever(self, project_id: str) -> "HybridRetriever | None": ...
